export const ACTION_CLIENT_TYPES = {

    CREATE_CLIENT: 'CREATE_CLIENT',
    UPDATE_CLIENT: 'UPDATE_CLIENT',
    DELETE_CLIENT: 'DELETE_CLIENT',
    FETCH_ALL_CLIENT: 'FETCH_ALL_CLIENT'
}


export const ACTION_STAFF_TYPES = {

    CREATE_STAFF: 'CREATE_STAFF',
    UPDATE_STAFF: 'UPDATE_STAFF',
    DELETE_STAFF: 'DELETE_STAFF',
    FETCH_ALL_STAFF: 'FETCH_ALL_STAFF'
}



export const ACTION_BRANCH_TYPES = {

    CREATE_BRANCH: 'CREATE_BRANCH',
    UPDATE_BRANCH: 'UPDATE_BRANCH',
    DELETE_BRANCH: 'DELETE_BRANCH',
    FETCH_ALL_BRANCH: 'FETCH_ALL_BRANCH'
}
